customhost = "employee-m.c0owxjwoh7um.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3113"
customdb = "employee"
custombucket = "tengjinlun-employee"
customregion = "us-east-1"
