customhost = "database-1.c0owxjwoh7um.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "tengjinlun-employee"
customregion = "us-east-1"
